import "./globals.css";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { authOptions } from "./api/auth/[...nextauth]/route";
import AuthContext from "@/Context/AuthContext";
import { ThemeProvider } from "@/Context/theme-provider";
import AuthLayout from "@/Context/AuthLayout";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Prompt.ai",
  description: "Generated by create next app",
};

export default async function RootLayout(props: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext session={session}>
          <AuthLayout>
            <Toaster />
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              {props.children}
              {props.modal}
              {/* <Sidebar>
              <Navbar logo="PrompAi" />
              <div className="p-4 sm:ml-64 mt-[64px]">{props.children}</div>
              {props.modal}
            </Sidebar> */}
            </ThemeProvider>
          </AuthLayout>
        </AuthContext>
      </body>
    </html>
  );
}
